# Generated by Django 4.2.5 on 2024-04-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('team_lead', models.CharField(max_length=400)),
                ('contact', models.CharField(max_length=400)),
                ('google_map', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=400)),
                ('documents', models.CharField(max_length=400)),
                ('landmarks', models.CharField(max_length=400)),
                ('features', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=0, max_digits=100)),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('google_map', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('contact', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Abia', 'Umuahia'), ('Abia', 'Umuahia'), ('Abia', 'Umuahia')], max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_image')),
                ('invite', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('receipt', models.ImageField(upload_to='receipt')),
            ],
        ),
    ]
