# Generated by Django 4.2.5 on 2024-04-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='subscription_form',
            field=models.FileField(blank=True, upload_to='subscription'),
        ),
    ]
