# Generated by Django 4.2.5 on 2024-04-02 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_estate_subscription_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtor',
            name='receipt',
            field=models.ImageField(blank=True, upload_to='receipt'),
        ),
    ]
