# Generated by Django 4.2.5 on 2024-04-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_realtor_gender_alter_realtor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='invite_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realtor',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_image'),
        ),
    ]
