# Generated by Django 4.2.5 on 2024-04-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_realtor_invite_contact_realtor_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='c_of_o',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='realtor',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='subscription_form',
            field=models.FileField(blank=True, null=True, upload_to='subscription'),
        ),
    ]
