# Generated by Django 4.2.5 on 2024-04-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_alter_estate_image_alter_estate_subscription_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='estate_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
