# Generated by Django 4.2.5 on 2024-04-05 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_purchase_estate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='days_of_meeting',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='google_map',
            field=models.TextField(blank=True, default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.1646936597103!2d7.084985270106946!3d6.242013912575235!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1043838870493793%3A0x8812a56a24e2139d!2sIzunna%20Hospital%20And%20Maternity!5e0!3m2!1sen!2sng!4v1712316657373!5m2!1sen!2sng" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_image'),
        ),
    ]
